package com.mandychev.foodfacts.vo

import com.google.gson.annotations.SerializedName

data class Nutriments(
        @SerializedName("carbohydrates") val carbohydrates: Double?,
        @SerializedName("carbohydrates_100g") val carbohydrates100g: Double?,
        @SerializedName("carbohydrates_serving") val carbohydratesServing: Double?,
        @SerializedName("carbohydrates_unit") val carbohydratesUnit: String?,
        @SerializedName("carbohydrates_value") val carbohydratesValue: String?,
        @SerializedName("energy") val energy: String?,
        @SerializedName("energy_100g") val energy100g: String?,
        @SerializedName("energy_serving") val energyServing: String?,
        @SerializedName("energy_unit") val energyUnit: String?,
        @SerializedName("energy_value") val energyValue: String?,
        @SerializedName("fat") val fat: Double?,
        @SerializedName("fat_100g") val fat100g: Double?,
        @SerializedName("fat_serving") val fatServing: Double?,
        @SerializedName("fat_unit") val fatUnit: String?,
        @SerializedName("fat_value") val fatValue: String?,
        @SerializedName("fiber") val fiber: Double?,
        @SerializedName("fiber_100g") val fiber100g: Double?,
        @SerializedName("fiber_serving") val fiberServing: Double?,
        @SerializedName("fiber_unit") val fiberUnit: String?,
        @SerializedName("fiber_value") val fiberValue: String?,
        @SerializedName("nova-group") val novaGroup: String?,
        @SerializedName("nova-group_100g") val novaGroup100g: String?,
        @SerializedName("nova-group_serving") val novaGroupServing: String?,
        @SerializedName("nutrition-score-fr") val nutritionScoreFr: String?,
        @SerializedName("nutrition-score-fr_100g") val nutritionScoreFr100g: String?,
        @SerializedName("nutrition-score-uk") val nutritionScoreUk: String?,
        @SerializedName("nutrition-score-uk_100g") val nutritionScoreUk100g: String?,
        @SerializedName("proteins") val proteins: Double?,
        @SerializedName("proteins_100g") val proteins100g: Double?,
        @SerializedName("proteins_serving") val proteinsServing: Double?,
        @SerializedName("proteins_unit") val proteinsUnit: String?,
        @SerializedName("proteins_value") val proteinsValue: String?,
        @SerializedName("salt") val salt: Double?,
        @SerializedName("salt_100g") val salt100g: Double?,
        @SerializedName("salt_serving") val saltServing: Double?,
        @SerializedName("salt_unit") val saltUnit: String?,
        @SerializedName("salt_value") val saltValue: String?,
        @SerializedName("saturated-fat") val saturatedFat: Double?,
        @SerializedName("saturated-fat_100g") val saturatedFat100g: Double?,
        @SerializedName("saturated-fat_serving") val saturatedFatServing: Double?,
        @SerializedName("saturated-fat_unit") val saturatedFatUnit: String?,
        @SerializedName("saturated-fat_value") val saturatedFatValue: String?,
        @SerializedName("sodium") val sodium: Double?,
        @SerializedName("sodium_100g") val sodium100g: Double?,
        @SerializedName("sodium_serving") val sodiumServing: Double?,
        @SerializedName("sugars") val sugars: Double?,
        @SerializedName("sugars_100g") val sugars100g: Double?,
        @SerializedName("sugars_serving") val sugarsServing: Double?,
        @SerializedName("sugars_unit") val sugarsUnit: String?,
        @SerializedName("sugars_value") val sugarsValue: String?
)